### ISSUE TITLE
Setup initial webpack with single entry

### ISSUE THREAD

**Issue by romeobleonor** [romeobleonor/ui_demo#1]
- Test how to submit issue.
- Please create a simple webpack.config with single entry and bundle to a folder called build

@igMarketingLeonor @romeobleonor

https://github.com/romeobleonor/ui_demo/blob/master/accordion_demo/index.html#L17

```
  module.exports = {

   entry: { },
   output: { }

   }
```

This is a sample of webpack module using `commonJS`.

**Comment by igMarketingLeonor** [comment]
I'll create that tomorrow at the office.

**Comment by romeobleonor** [comment]
Thanks! I've already started it. I'll keep you posted if there is any issue I come across.

**Comment by romeobleonor** [comment]
Webpack config with single entry has been created. Below is the simple snippets. 

```
module.exports = {

    entry: {
        main: ['./static/scripts/main.js']
    },
    output: {
        filename: '[name].js',
        path: path.join(__dirname, './build'),
        publicPath: './build'
    }
}
```
