### ISSUE TITLE
Create a bare bone webpack config to demonstrate hot reload module

### ISSUE THREAD

**Issue by romeobleonor** [romeobleonor/ui_demo#4]
Create hotReloadDemo folder to demonstrate hot reload. 

@igMarketingLeonor

**Comment by igMarketingLeonor** [comment]
As requested, I've created a demo for Hot Reload Module Replacement Plugin
- Create an index.html with script which refers to the publicPath

```
// index.html
<script src="/hotDev/main.js"></script>
```
- Our entry script is located at src/scripts/main.js

```
// onload event
document.body.onload = addElement;
function addElement(){
   var content = document.createTextNode('Dynamic content which will be added to the h1');
   var newElem = document.createElement('h1');
   newElem.appendChild(content);

   var wrapper = document.getElementsByClassName('wrapper')[0];
   wrapper.appendChild(newElem)
}
```
- Setup a webpack configuration
  - entry property is set to call a function that load other entry scripts, we add dev entries which is require by hot reload module plugin
  - output property where all the builds located
    - publicPath execute during hot reload
    - filename follows the script filename convention
    - path indicates where the folder will generate

```
output: {
  filename: '[name].js',
  publicPath: '/hotDev',
  path: path.join(__dirname, 'build')
}
```
- plugins holds an array which contains an instance of your plugins, such as HotReloadModuleReplacement

```
plugins: [
  new webpack.HotModuleReplacementPlugin()
]
```
